"""
Empirical Verification & Stress Test Harness for Proposition 1 and Theorem 2.

Author: Challenger 1 (Milestone M1)
Verification Scope:
1. Proposition 1: Non-Zero Intrusion Probability and Gradient Conflict Dynamics
   - In low and high dimensional manifolds separated by Delta_AB > 0, uncoordinated pseudo-negatives
     generated by Client A that intrude onto Client B's benign manifold M_B induce an antagonistic
     gradient direction <grad_L_A^anom, grad_L_B^norm> < 0 with cosine approaching -1.0.
   - When intrusion dominates concordant terms, net client gradients satisfy <grad_L_A, grad_L_B> < 0.
2. Theorem 2: Cross-Manifold Negative Purging (CMNP) Eradicates Antagonism
   - FSDS peer sketches S_B actively detect and purge intruding pseudo-negative candidates.
   - Purging eliminates the cross-manifold conflicting term (mu_int^purged = 0), reducing or
     completely reversing the negative gradient inner product (cos >= 0).
"""

import pytest
import numpy as np
import torch
import torch.nn as nn
from typing import Dict, List, Tuple, Any

from fed_lunar.models.lunar_mlp import LUNAR_MLP, KNNDistanceExtractor, LunarDistanceRankingLoss
from fed_lunar.models.negative_gen import SubspaceNegativeGenerator, CMNPFilter
from fed_lunar.federated.sketches import FSDSSketch, compute_fsds_sketch
from fed_lunar.federated.strategy import compute_gradient_conflict_metrics


def generate_non_iid_cluster_manifolds(
    n_a: int = 150,
    n_b: int = 150,
    dim: int = 8,
    rank: int = 3,
    delta_ab: float = 1.0,
    std_a: float = 0.05,
    std_b: float = 0.20,
    seed: int = 42,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Generate synthetic non-IID benign manifolds M_A and M_B in R^D separated by delta_ab.
    M_A is a dense benign manifold centered at the origin.
    M_B is a sparse benign manifold centered at mu_B = [delta_ab, 0, ..., 0].
    """
    rng = np.random.RandomState(seed)

    mu_A = np.zeros(dim, dtype=np.float32)
    mu_B = np.zeros(dim, dtype=np.float32)
    mu_B[0] = delta_ab

    # Subspace bases
    Q_A, _ = np.linalg.qr(rng.randn(dim, rank))
    Q_B, _ = np.linalg.qr(rng.randn(dim, rank))
    U_A = Q_A[:, :rank].astype(np.float32)
    U_B = Q_B[:, :rank].astype(np.float32)

    # Coordinates in tangent space
    coords_A = rng.randn(n_a, rank).astype(np.float32) * std_a
    coords_B = rng.randn(n_b, rank).astype(np.float32) * std_b

    noise_A = rng.randn(n_a, dim).astype(np.float32) * (std_a * 0.2)
    noise_B = rng.randn(n_b, dim).astype(np.float32) * (std_b * 0.2)

    X_A = mu_A + coords_A @ U_A.T + noise_A
    X_B = mu_B + coords_B @ U_B.T + noise_B

    return X_A, X_B, U_A, U_B


def compute_gradient_flat(
    model: LUNAR_MLP,
    loss: torch.Tensor,
) -> torch.Tensor:
    """Compute and flatten parameter gradients."""
    model.zero_grad()
    loss.backward()
    grads = []
    for p in model.parameters():
        if p.grad is not None:
            grads.append(p.grad.detach().view(-1))
        else:
            grads.append(torch.zeros(p.numel(), device=p.device))
    return torch.cat(grads).clone()


class TestEmpiricalProposition1AndTheorem2:
    """Empirical verification suite for Proposition 1 and Theorem 2."""

    def test_proposition_1_microscopic_gradient_conflict(self):
        """
        Verify Proposition 1 (Microscopic Cross-Manifold Term):
        Pseudo-negatives generated on Client A that land inside Client B's benign manifold M_B
        produce a gradient that is strictly antagonistic to Client B's normal gradient:
        <g_A^intrude, g_B^norm> < 0, with cosine similarity strongly negative (cos < -0.80).
        """
        torch.manual_seed(42)
        np.random.seed(42)
        dim = 8
        k = 5
        N = 120

        X_A, X_B, U_A, U_B = generate_non_iid_cluster_manifolds(
            n_a=N, n_b=N, dim=dim, rank=3, delta_ab=1.5, std_a=0.1, std_b=0.2, seed=42
        )
        sketch_B = compute_fsds_sketch(X_B, client_id="B", rank=3)

        knn_A = KNNDistanceExtractor(X_A)
        knn_B = KNNDistanceExtractor(X_B)

        # Generate intrusive pseudo-negatives that fall directly into M_B
        mu_B = np.zeros(dim, dtype=np.float32)
        mu_B[0] = 1.5
        neg_intrusive_A = np.random.randn(80, dim).astype(np.float32) * 0.15 + mu_B

        # Verify intrusion measure under FSDS sketch
        intrusions = sketch_B.is_intruding(neg_intrusive_A, tau_null=1.5, alpha=0.01)
        intrusion_ratio = np.mean(intrusions)
        assert intrusion_ratio >= 0.50, f"Expected substantial intrusion rate into B, got {intrusion_ratio:.2f}"

        model = LUNAR_MLP(k=k, hidden_dims=[32, 16], dropout=0.0)

        # Distance vectors
        d_intrusive_A = knn_A(neg_intrusive_A, k=k, is_reference_member=False)
        d_norm_B = knn_B(X_B, k=k, is_reference_member=True)

        # Gradient of intrusive negatives on Client A (target y=1)
        loss_A_intrude = torch.nn.functional.binary_cross_entropy_with_logits(
            model(d_intrusive_A), torch.ones(len(neg_intrusive_A), 1)
        )
        g_A_intrude = compute_gradient_flat(model, loss_A_intrude)

        # Gradient of benign samples on Client B (target y=0)
        loss_B_norm = torch.nn.functional.binary_cross_entropy_with_logits(
            model(d_norm_B), torch.zeros(len(X_B), 1)
        )
        g_B_norm = compute_gradient_flat(model, loss_B_norm)

        cos_micro = torch.dot(g_A_intrude, g_B_norm) / (torch.norm(g_A_intrude) * torch.norm(g_B_norm) + 1e-12)
        inner_micro = torch.dot(g_A_intrude, g_B_norm).item()

        print(f"\n[Microscopic Gradient Conflict]")
        print(f"Intrusion ratio mu_int(A -> B): {intrusion_ratio*100:.1f}%")
        print(f"Inner Product <g_A^intrude, g_B^norm>: {inner_micro:.6f}")
        print(f"Cosine Similarity cos(g_A^intrude, g_B^norm): {cos_micro.item():+.6f}")

        # Strict empirical challenge assertions
        assert inner_micro < 0.0, "Microscopic inner product must be strictly negative"
        assert cos_micro.item() < -0.50, f"Cosine similarity must be strongly negative, got {cos_micro.item()}"

    def test_theorem_2_cmnp_purging_and_gradient_conflict_resolution(self):
        """
        Verify Theorem 2 (CMNP Purging Eradicates Conflict):
        1. Peer sketch S_B detects and purges 100% of intruding candidates.
        2. Unpurged naive generator yields negative cosine similarity between clients (<grad_A, grad_B> < 0).
        3. CMNP purging eliminates the conflict, strictly increasing cosine similarity (cos >= 0).
        """
        torch.manual_seed(42)
        np.random.seed(42)
        dim = 4
        k = 5
        N = 100

        # Create density-scale non-IID setup
        X_A = np.random.randn(N, dim).astype(np.float32) * 0.02
        mu_B = np.array([0.5, 0.0, 0.0, 0.0], dtype=np.float32)
        X_B = np.random.randn(N, dim).astype(np.float32) * 0.25 + mu_B

        sketch_B = compute_fsds_sketch(X_B, client_id="B", rank=2)
        knn_A = KNNDistanceExtractor(X_A)
        knn_B = KNNDistanceExtractor(X_B)

        # Candidate pseudo-negatives: 50 intrusive onto B, 50 safe outside B
        cand_intrusive = np.random.randn(50, dim).astype(np.float32) * 0.15 + mu_B
        mu_safe = np.array([0.0, 0.0, 1.5, 0.0], dtype=np.float32)
        cand_safe = np.random.randn(50, dim).astype(np.float32) * 0.15 + mu_safe
        all_candidates = np.vstack([cand_intrusive, cand_safe])

        # Filter candidates using CMNP with S_B
        cmnp = CMNPFilter(peer_sketches=[sketch_B], tau_null=1.5, alpha=0.01)
        purged_candidates, stats = cmnp.filter_candidates(all_candidates)

        # 1. Verify Purging Guarantees
        assert stats["rejected"] == 50, f"CMNP must reject exactly all 50 intrusive points, rejected {stats['rejected']}"
        assert stats["accepted"] == 50, f"CMNP must accept exactly the 50 safe points, accepted {stats['accepted']}"
        remaining_intrusions = sketch_B.is_intruding(purged_candidates, tau_null=1.5, alpha=0.01)
        assert np.sum(remaining_intrusions) == 0, "Accepted set must contain 0 intrusive points"

        # 2. Verify Gradient Dynamics
        model = LUNAR_MLP(k=k, hidden_dims=[32, 16], dropout=0.0)
        criterion = LunarDistanceRankingLoss()

        # Client B update
        neg_B = np.random.randn(N, dim).astype(np.float32) * 0.3 + mu_B + np.array([0.0, 1.5, 0.0, 0.0], dtype=np.float32)
        d_norm_B = knn_B(X_B, k=k, is_reference_member=True)
        d_anom_B = knn_B(neg_B, k=k, is_reference_member=False)
        loss_B = criterion(model(d_norm_B), model(d_anom_B), lambda_anom=0.1)
        g_B = compute_gradient_flat(model, loss_B)

        # Client A Naive (using intrusive pseudo-negatives)
        d_norm_A = knn_A(X_A, k=k, is_reference_member=True)
        d_anom_naive = knn_A(cand_intrusive, k=k, is_reference_member=False)
        loss_A_naive = criterion(model(d_norm_A), model(d_anom_naive), lambda_anom=1.0)
        g_A_naive = compute_gradient_flat(model, loss_A_naive)

        # Client A CMNP (using purged safe pseudo-negatives)
        d_anom_purged = knn_A(purged_candidates, k=k, is_reference_member=False)
        loss_A_purged = criterion(model(d_norm_A), model(d_anom_purged), lambda_anom=1.0)
        g_A_purged = compute_gradient_flat(model, loss_A_purged)

        cos_naive = torch.dot(g_A_naive, g_B) / (torch.norm(g_A_naive) * torch.norm(g_B))
        cos_purged = torch.dot(g_A_purged, g_B) / (torch.norm(g_A_purged) * torch.norm(g_B))

        print(f"\n[Gradient Conflict & Resolution]")
        print(f"Naive Cosine (Unpurged Intrusion): {cos_naive.item():+.6f}")
        print(f"Purged Cosine (CMNP Active):       {cos_purged.item():+.6f}")
        print(f"Improvement Delta Cosine:          {(cos_purged - cos_naive).item():+.6f}")

        # Assertions
        assert cos_naive.item() < 0.0, f"Naive intrusive negatives must induce gradient conflict (< 0), got {cos_naive.item()}"
        assert cos_purged.item() > 0.0, f"CMNP purged negatives must yield non-conflicting cosine (> 0), got {cos_purged.item()}"
        assert cos_purged.item() > cos_naive.item(), "CMNP must strictly improve gradient cosine similarity"

    def test_multi_seed_stress_harness(self):
        """
        Statistical stress test across 10 random seeds.
        Demonstrates that gradient conflict consistently occurs under naive intrusion,
        and CMNP consistently purges intrusions and eliminates gradient conflict.
        """
        dim = 4
        k = 5
        N = 80
        seeds = range(100, 110)

        naive_cosines = []
        purged_cosines = []
        rejection_ratios = []

        for seed in seeds:
            torch.manual_seed(seed)
            np.random.seed(seed)

            X_A = np.random.randn(N, dim).astype(np.float32) * 0.02
            mu_B = np.array([0.5, 0.0, 0.0, 0.0], dtype=np.float32)
            X_B = np.random.randn(N, dim).astype(np.float32) * 0.25 + mu_B

            sketch_B = compute_fsds_sketch(X_B, client_id="B", rank=2)
            knn_A = KNNDistanceExtractor(X_A)
            knn_B = KNNDistanceExtractor(X_B)

            cand_intrusive = np.random.randn(40, dim).astype(np.float32) * 0.15 + mu_B
            mu_safe = np.array([0.0, 0.0, 1.5, 0.0], dtype=np.float32)
            cand_safe = np.random.randn(40, dim).astype(np.float32) * 0.15 + mu_safe
            all_candidates = np.vstack([cand_intrusive, cand_safe])

            cmnp = CMNPFilter(peer_sketches=[sketch_B], tau_null=1.5, alpha=0.01)
            purged, stats = cmnp.filter_candidates(all_candidates)
            rejection_ratios.append(stats["rejection_rate"])

            model = LUNAR_MLP(k=k, hidden_dims=[32, 16], dropout=0.0)
            criterion = LunarDistanceRankingLoss()

            # Client B
            neg_B = np.random.randn(N, dim).astype(np.float32) * 0.3 + mu_B + np.array([0.0, 1.5, 0.0, 0.0], dtype=np.float32)
            loss_B = criterion(model(knn_B(X_B, k=k, is_reference_member=True)), model(knn_B(neg_B, k=k, is_reference_member=False)), lambda_anom=0.1)
            g_B = compute_gradient_flat(model, loss_B)

            # Client A Naive
            loss_A_naive = criterion(model(knn_A(X_A, k=k, is_reference_member=True)), model(knn_A(cand_intrusive, k=k, is_reference_member=False)), lambda_anom=1.0)
            g_A_naive = compute_gradient_flat(model, loss_A_naive)

            # Client A Purged
            loss_A_purged = criterion(model(knn_A(X_A, k=k, is_reference_member=True)), model(knn_A(purged, k=k, is_reference_member=False)), lambda_anom=1.0)
            g_A_purged = compute_gradient_flat(model, loss_A_purged)

            cos_n = torch.dot(g_A_naive, g_B) / (torch.norm(g_A_naive) * torch.norm(g_B))
            cos_p = torch.dot(g_A_purged, g_B) / (torch.norm(g_A_purged) * torch.norm(g_B))

            naive_cosines.append(cos_n.item())
            purged_cosines.append(cos_p.item())

        print("\n[Statistical Multi-Seed Stress Harness (10 seeds)]")
        print(f"Naive Cosine Mean:  {np.mean(naive_cosines):+.6f} +/- {np.std(naive_cosines):.4f}")
        print(f"Purged Cosine Mean: {np.mean(purged_cosines):+.6f} +/- {np.std(purged_cosines):.4f}")
        print(f"Conflict Resolution Rate: {np.mean(np.array(purged_cosines) > 0.0) * 100:.1f}%")
        print(f"Average Purge Rejection Rate: {np.mean(rejection_ratios):.1f}%")

        # Theorem 2 Guarantees:
        # 1. Unpurged pseudo-negative intrusion induces gradient conflict (mean cos < 0)
        assert np.mean(naive_cosines) < 0.0, "Mean naive cosine across seeds must be negative"
        # 2. Active purging rate is high across all seeds
        assert np.mean(rejection_ratios) > 30.0, "Average purge rejection rate must be substantial"
        # 3. CMNP strictly improves gradient cosine alignment in at least 90% of seeds
        deltas = np.array(purged_cosines) - np.array(naive_cosines)
        assert np.sum(deltas > 0.0) >= 9, f"CMNP must strictly improve cosine in >=90% of seeds, got {np.sum(deltas > 0.0)}/10"
        assert np.mean(deltas) > 0.02, f"Expected significant average improvement, got {np.mean(deltas):.4f}"
