"""
Unit tests for Federated Subspace Density Sketches (FSDS)
and Cross-Manifold Negative Purging (CMNP).

Reference:
    Explorer 3 Report (Mathematical Foundations), Algorithm 1 & Theorem 2.
"""

import pytest
import numpy as np
import torch

from fed_lunar.federated.sketches import FSDSSketch, compute_fsds_sketch
from fed_lunar.models.negative_gen import CMNPFilter, SubspaceNegativeGenerator


def test_fsds_sketch_computation_and_properties():
    """Test FSDS sketch statistical correctness, orthonormality, and tubular envelope bounds."""
    np.random.seed(42)
    N, D, r = 200, 12, 4

    # Generate synthetic clustered data with principal subspace
    U_true, _ = np.linalg.qr(np.random.randn(D, r))
    z = np.random.randn(N, r) * np.array([4.0, 2.0, 1.0, 0.5])
    noise = np.random.randn(N, D) * 0.05
    mu_true = np.linspace(1.0, 5.0, D)
    X = mu_true + z @ U_true.T + noise

    sketch = compute_fsds_sketch(X, client_id="client_0", rank=r, beta=2.0)

    # 1. Centroid check
    np.testing.assert_allclose(sketch.mu, np.mean(X, axis=0), atol=1e-5)

    # 2. Orthonormality check: U^T U == I_r
    UtU = sketch.U.T @ sketch.U
    np.testing.assert_allclose(UtU, np.eye(r), atol=1e-5)

    # 3. Eigenvalue positivity and descending order
    assert np.all(sketch.Lambda > 0.0)
    for i in range(r - 1):
        assert sketch.Lambda[i] >= sketch.Lambda[i + 1]

    # 4. Tubular envelope bound: all training samples should satisfy d_null(x_i) <= r_max
    d_nulls = sketch.null_space_distance(X)
    assert np.all(d_nulls <= sketch.r_max)
    assert sketch.r_max > 0.0

    # 5. Serialization round-trip
    sketch_dict = sketch.to_dict()
    restored = FSDSSketch.from_dict(sketch_dict)
    assert restored.client_id == sketch.client_id
    assert restored.r == sketch.r
    np.testing.assert_allclose(restored.mu, sketch.mu)
    np.testing.assert_allclose(restored.U, sketch.U)
    np.testing.assert_allclose(restored.Lambda, sketch.Lambda)
    assert restored.r_max == sketch.r_max


def test_null_space_and_subspace_distances():
    """Test algebraic properties of null-space distance and in-subspace Mahalanobis distance."""
    np.random.seed(123)
    D, r = 8, 3
    mu = np.zeros(D)
    U, _ = np.linalg.qr(np.random.randn(D, r))
    Lambda = np.array([3.0, 2.0, 1.0])
    r_max = 1.5

    sketch = FSDSSketch("test_c", mu, Lambda, U, r_max, r, n_samples=100)

    # Point in tangent subspace: x = U @ v
    v = np.array([1.0, 0.5, -0.5])
    x_subspace = U @ v
    d_null_sub = sketch.null_space_distance(x_subspace)[0]
    d_mah_sub = sketch.subspace_mahalanobis_distance(x_subspace)[0]

    # Null space distance should be zero (point lies entirely in subspace)
    assert d_null_sub < 1e-6
    # Mahalanobis distance should match sqrt(sum(v_i^2 / lambda_i))
    expected_mah = np.sqrt(np.sum((v ** 2) / Lambda))
    np.testing.assert_allclose(d_mah_sub, expected_mah, atol=1e-5)

    # Point in null space: orthogonal to all columns of U
    # Find orthogonal complement vector
    full_basis, _ = np.linalg.qr(U, mode="complete")
    null_basis = full_basis[:, r:]  # Columns r to D-1 are orthogonal to U
    w = null_basis[:, 0] * 2.0
    x_null = w

    d_null_null = sketch.null_space_distance(x_null)[0]
    d_mah_null = sketch.subspace_mahalanobis_distance(x_null)[0]

    np.testing.assert_allclose(d_null_null, 2.0, atol=1e-5)
    assert d_mah_null < 1e-6


def test_cmnp_hard_purging_disjoint_manifolds():
    """
    Test Theorem 2 & CMNP Filter:
    Pseudo-negatives generated by Client A that intrude into Client B's benign manifold
    are strictly detected and purged.
    """
    np.random.seed(42)
    D = 10
    N = 100

    # Client A manifold at origin [0, ..., 0]
    X_A = np.random.randn(N, D) * 0.1
    sketch_A = compute_fsds_sketch(X_A, client_id="client_A", rank=3)

    # Client B manifold at offset [10, ..., 10]
    X_B = np.random.randn(N, D) * 0.1 + 10.0
    sketch_B = compute_fsds_sketch(X_B, client_id="client_B", rank=3)

    # Setup CMNPFilter on Client A observing peer sketch B
    cmnp_filter = CMNPFilter(peer_sketches=[sketch_B], tau_null=1.0, alpha=0.01)

    # Candidate 1: safe perturbation around Client A
    cand_safe = np.random.randn(5, D) * 0.2  # Near origin
    # Candidate 2: intrusive perturbation falling right into Client B's manifold
    cand_intrusive = X_B[:5] + np.random.randn(5, D) * 0.02  # Close to Client B

    all_candidates = np.vstack([cand_safe, cand_intrusive])
    is_intruding = cmnp_filter.check_intrusion(all_candidates)

    # First 5 (safe) should NOT be intruding; last 5 (intrusive) MUST be intruding
    np.testing.assert_array_equal(is_intruding[:5], [False] * 5)
    np.testing.assert_array_equal(is_intruding[5:], [True] * 5)

    # Filter candidates
    purged, stats = cmnp_filter.filter_candidates(all_candidates)
    assert purged.shape[0] == 5, f"Expected 5 accepted candidates, got {purged.shape[0]}"
    assert stats["total"] == 10
    assert stats["accepted"] == 5
    assert stats["rejected"] == 5
    assert stats["rejection_rate"] == 50.0

    # All purged candidates must match the safe ones
    np.testing.assert_allclose(purged, cand_safe, atol=1e-5)


def test_cmnp_continuous_soft_weighting():
    """Test soft debiasing continuous weights w(x_tilde) in [0, 1]."""
    np.random.seed(42)
    D = 8
    X_B = np.random.randn(50, D) * 0.1 + 5.0
    sketch_B = compute_fsds_sketch(X_B, client_id="B", rank=2)

    cmnp_filter = CMNPFilter(peer_sketches=[sketch_B], gamma=1.0)

    # Point right on Client B centroid
    point_on_B = sketch_B.mu.reshape(1, -1)
    # Point very far from Client B
    point_far = (sketch_B.mu + 50.0).reshape(1, -1)

    weights_on_B = cmnp_filter.compute_soft_weights(point_on_B)
    weights_far = cmnp_filter.compute_soft_weights(point_far)

    # Point on B should have near 0 weight (debiased / suppressed)
    assert weights_on_B[0] < 0.1, f"Expected small weight on B, got {weights_on_B[0]}"
    # Point far away should have weight close to 1.0 (unsuppressed)
    assert weights_far[0] > 0.99, f"Expected near 1.0 weight far from B, got {weights_far[0]}"


def test_subspace_negative_generator_fallback():
    """Test that when all candidates are purged, generator falls back to high-radius boundary noise."""
    np.random.seed(99)
    D = 6
    N = 30
    X_A = np.random.randn(N, D) * 0.05
    sketch_A = compute_fsds_sketch(X_A, client_id="A", rank=2)

    # Create an artificial sketch covering the entire local region to force 100% rejection
    sketch_trap = FSDSSketch(
        client_id="trap",
        mu=np.zeros(D),
        Lambda=np.ones(2) * 100.0,
        U=sketch_A.U,
        r_max=100.0,  # Huge envelope that traps everything
        r=2,
        n_samples=N,
    )

    cmnp_filter = CMNPFilter(peer_sketches=[sketch_trap], tau_null=1.0)
    gen = SubspaceNegativeGenerator(
        negative_ratio=1.0,
        sigma_pert=0.1,
        cmnp_filter=cmnp_filter,
        subspace_U=sketch_A.U,
    )

    negatives, stats = gen.generate(X_A)
    assert stats["fallback_used"] is True, "Fallback should be activated when all candidates are purged"
    assert negatives.shape[0] == N
    # Fallback points should have large distance from anchors
    distances = np.linalg.norm(negatives - X_A, axis=1)
    assert np.all(distances >= 0.15), "Fallback noise should place points at boundary"


def test_theorem_2_cmnp_eliminates_antagonism():
    """
    Direct empirical verification of Theorem 2 (Purging Eradicates Cross-Manifold Antagonism).
    Shows that purging prevents intruding pseudo-negatives from corrupting peer distance ranking.
    """
    np.random.seed(42)
    D = 2
    N = 100

    # Client A: Gaussian cluster at [0, 0]
    X_A = np.random.randn(N, D) * 0.3
    # Client B: Gaussian cluster at [1.0, 1.0] (partially overlapping under large perturbation)
    X_B = np.random.randn(N, D) * 0.3 + np.array([1.0, 1.0])

    sketch_B = compute_fsds_sketch(X_B, client_id="B", rank=2)

    # Generator with CMNP
    cmnp_filter = CMNPFilter(peer_sketches=[sketch_B], tau_null=1.5, alpha=0.05)
    cmnp_gen = SubspaceNegativeGenerator(
        negative_ratio=2.0, sigma_pert=1.0, cmnp_filter=cmnp_filter, mode="isotropic", seed=42
    )
    cmnp_neg, stats = cmnp_gen.generate(X_A)

    # Generator without CMNP (Naive baseline)
    naive_gen = SubspaceNegativeGenerator(
        negative_ratio=2.0, sigma_pert=1.0, cmnp_filter=None, mode="isotropic", seed=42
    )
    naive_neg, _ = naive_gen.generate(X_A)

    # Measure minimum distance of generated negatives to Client B's normal points
    min_dist_naive_to_B = np.min(np.linalg.norm(naive_neg[:, None, :] - X_B[None, :, :], axis=-1))
    min_dist_cmnp_to_B = np.min(np.linalg.norm(cmnp_neg[:, None, :] - X_B[None, :, :], axis=-1))

    # CMNP generator enforces a safety buffer around Client B by purging intruding points
    assert stats["rejected"] > 0, f"CMNP should reject intruding candidates, stats: {stats}"
    assert min_dist_cmnp_to_B > min_dist_naive_to_B
